### ISSUE TITLE
Use comma ok idiom

### ISSUE THREAD

**Issue by Henry-Sarabia** [willdot/NotARealServer#8]
https://github.com/willdot/NotARealServer/blob/0630f6e3f91ca3eab21fcc3a3265437497f97768/handlers/persistRequestHandler.go#L49

In Go, there is what's called the "comma ok" idiom. When reading from a built-in operation such as reading from a map, channel, or making a type assertion, it is typical to use the comma ok idiom. 

Basically, you write a statement with two variables, the first of which being the value you are trying to read and the second of which being the bool reporting whether or not the value exists.

Your code achieves the same goal but is not idiomatic. You can read about the comma ok idiom [here](https://golang.org/doc/effective_go.html#maps)

**Comment by willdot** [comment]
Thanks 👍
